---
# For docker image tags see https://hub.docker.com/_/maven/
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
#
# This template will build the project
#
# * Caches downloaded dependencies and plugins between invocation.

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"



# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  key: m2repo
  paths:
    - src/.m2/repository

build:
  before_script:
    - cd src/de.unidue.stud.sehawagn.openhab.binding.wmbus.p2site
    - mvn clean install p2:site
    - cd ../../
  script:
    - cd src
    - 'mvn $MAVEN_CLI_OPTS package'
  artifacts:
    paths:
    - src/de.unidue.stud.sehawagn.openhab.binding.wmbus/target/*.jar
  image: maven:3.5-jdk-8
